import { AlumniProfile } from "./types";

export const sampleAlumni: AlumniProfile[] = [
  {
    id: "1",
    full_name: "Olivia Chen",
    undergraduate_degree: "BSc Computer Science",
    university: "Imperial College London",
    location_city: "London",
    location_country: "United Kingdom",
    latitude: 51.5074,
    longitude: -0.1278,
    graduation_year: 2018,
    hl_subjects: ["Mathematics", "Physics", "Computer Science"],
    hl_teachers: ["Mr. Thompson", "Dr. Patel"],
    current_profession: "Software Engineer at DeepMind",
    advice_to_students:
      "Don't be afraid to take the unconventional path. The IB teaches you how to think, not what to think -- that's your superpower.",
    favourite_memory:
      "Late-night TOK debates in the common room that turned into impromptu philosophy sessions.",
    took_gap_year: false,
    interesting_first_year_class: "Introduction to Machine Learning",
    linkedin_url: "https://linkedin.com/in/oliviachen",
    open_to_contact: true,
    open_to_mentoring: true,
    consent_given: true,
    status: "approved",
    created_at: "2024-01-15T10:00:00Z",
  },
  {
    id: "2",
    full_name: "James Rodriguez",
    undergraduate_degree: "BA Economics",
    university: "Columbia University",
    location_city: "New York",
    location_country: "United States",
    latitude: 40.7128,
    longitude: -74.006,
    graduation_year: 2016,
    hl_subjects: ["Economics", "Mathematics", "English Literature"],
    hl_teachers: ["Ms. Williams", "Mr. Garcia"],
    current_profession: "Investment Analyst at Goldman Sachs",
    advice_to_students:
      "Your Extended Essay topic doesn't define your career. I wrote about Shakespeare and ended up in finance. Follow your curiosity.",
    favourite_memory:
      "The Year 13 trip to Barcelona where our Spanish teacher let us navigate the city entirely in Spanish.",
    took_gap_year: true,
    interesting_first_year_class: "Behavioural Economics",
    linkedin_url: "https://linkedin.com/in/jamesrodriguez",
    open_to_contact: true,
    open_to_mentoring: false,
    consent_given: true,
    status: "approved",
    created_at: "2024-02-10T14:30:00Z",
  },
  {
    id: "3",
    full_name: "Aisha Tan",
    undergraduate_degree: "BBA Business Administration",
    university: "National University of Singapore",
    location_city: "Singapore",
    location_country: "Singapore",
    latitude: 1.3521,
    longitude: 103.8198,
    graduation_year: 2019,
    hl_subjects: ["Business Management", "Mathematics", "Chinese B"],
    hl_teachers: ["Mr. Lee", "Ms. Zhang"],
    current_profession: "Product Manager at Grab",
    advice_to_students:
      "CAS hours feel tedious at the time, but the skills you build -- leadership, empathy, resilience -- are exactly what employers look for.",
    favourite_memory:
      "Organising the international food festival and watching the whole school come together.",
    took_gap_year: false,
    interesting_first_year_class: "Design Thinking for Innovation",
    linkedin_url: "https://linkedin.com/in/aishatan",
    open_to_contact: true,
    open_to_mentoring: true,
    consent_given: true,
    status: "approved",
    created_at: "2024-03-05T09:15:00Z",
  },
  {
    id: "4",
    full_name: "Felix Hoffmann",
    undergraduate_degree: "BSc Mechanical Engineering",
    university: "Technical University of Munich",
    location_city: "Berlin",
    location_country: "Germany",
    latitude: 52.52,
    longitude: 13.405,
    graduation_year: 2017,
    hl_subjects: ["Physics", "Mathematics", "Design Technology"],
    hl_teachers: ["Dr. Mueller", "Mr. Thompson"],
    current_profession: "Renewable Energy Engineer at Siemens",
    advice_to_students:
      "The Group 4 project taught me more about teamwork than any university course. Take it seriously.",
    favourite_memory:
      "Building our solar-powered boat for the DT exhibition and actually getting it to float.",
    took_gap_year: true,
    interesting_first_year_class: "Thermodynamics and Energy Systems",
    linkedin_url: "https://linkedin.com/in/felixhoffmann",
    open_to_contact: true,
    open_to_mentoring: true,
    consent_given: true,
    status: "approved",
    created_at: "2024-01-22T11:45:00Z",
  },
  {
    id: "5",
    full_name: "Sophie Clarke",
    undergraduate_degree: "BA Architecture",
    university: "University of Sydney",
    location_city: "Sydney",
    location_country: "Australia",
    latitude: -33.8688,
    longitude: 151.2093,
    graduation_year: 2020,
    hl_subjects: ["Visual Arts", "Mathematics", "Physics"],
    hl_teachers: ["Ms. O'Brien", "Mr. Thompson"],
    current_profession: "Junior Architect at BVN Architecture",
    advice_to_students:
      "Your HL Visual Arts portfolio is genuinely useful for university applications. Put your heart into it.",
    favourite_memory:
      "The art exhibition in Year 13 -- seeing months of work displayed in the gallery was incredibly rewarding.",
    took_gap_year: false,
    interesting_first_year_class: "History of Modern Architecture",
    linkedin_url: null,
    open_to_contact: true,
    open_to_mentoring: false,
    consent_given: true,
    status: "approved",
    created_at: "2024-04-01T08:00:00Z",
  },
  {
    id: "6",
    full_name: "Kenji Nakamura",
    undergraduate_degree: "BSc Biomedical Science",
    university: "University of Tokyo",
    location_city: "Tokyo",
    location_country: "Japan",
    latitude: 35.6762,
    longitude: 139.6503,
    graduation_year: 2015,
    hl_subjects: ["Biology", "Chemistry", "Mathematics"],
    hl_teachers: ["Dr. Sato", "Ms. Patel"],
    current_profession: "Research Scientist at RIKEN",
    advice_to_students:
      "HL Biology and Chemistry together is brutal, but it gave me a foundation that most of my university peers didn't have.",
    favourite_memory:
      "Dissecting a sheep's heart in Biology and our teacher surprising us with a real surgeon to explain the procedure.",
    took_gap_year: false,
    interesting_first_year_class: "Molecular Biology of the Cell",
    linkedin_url: "https://linkedin.com/in/kenjinakamura",
    open_to_contact: true,
    open_to_mentoring: true,
    consent_given: true,
    status: "approved",
    created_at: "2024-02-28T16:20:00Z",
  },
  {
    id: "7",
    full_name: "Fatima Al-Rashid",
    undergraduate_degree: "BA International Relations",
    university: "Sciences Po Paris",
    location_city: "Dubai",
    location_country: "United Arab Emirates",
    latitude: 25.2048,
    longitude: 55.2708,
    graduation_year: 2018,
    hl_subjects: ["History", "English Literature", "French B"],
    hl_teachers: ["Mr. Dubois", "Ms. Williams"],
    current_profession: "Policy Analyst at UN Development Programme",
    advice_to_students:
      "Model UN is not just an extracurricular -- it's career training. I use those skills every single day.",
    favourite_memory:
      "Winning Best Delegate at THIMUN and celebrating with the whole team at a restaurant in The Hague.",
    took_gap_year: true,
    interesting_first_year_class: "Diplomacy and Negotiation",
    linkedin_url: "https://linkedin.com/in/fatimaalrashid",
    open_to_contact: true,
    open_to_mentoring: true,
    consent_given: true,
    status: "approved",
    created_at: "2024-03-15T13:10:00Z",
  },
  {
    id: "8",
    full_name: "Marcus Wei",
    undergraduate_degree: "BSc Data Science",
    university: "Stanford University",
    location_city: "San Francisco",
    location_country: "United States",
    latitude: 37.7749,
    longitude: -122.4194,
    graduation_year: 2019,
    hl_subjects: ["Mathematics", "Computer Science", "Economics"],
    hl_teachers: ["Mr. Thompson", "Ms. Williams"],
    current_profession: "Data Scientist at Stripe",
    advice_to_students:
      "Learn to code even if it's not your HL. I started with a simple CAS project building a school website and it changed my career trajectory.",
    favourite_memory:
      "The maths competition team making it to the finals and Mr. Thompson buying us all pizza to celebrate.",
    took_gap_year: false,
    interesting_first_year_class: "Statistical Learning Theory",
    linkedin_url: "https://linkedin.com/in/marcuswei",
    open_to_contact: true,
    open_to_mentoring: true,
    consent_given: true,
    status: "approved",
    created_at: "2024-01-08T10:30:00Z",
  },
  {
    id: "9",
    full_name: "Camille Dubois",
    undergraduate_degree: "BA Film Studies",
    university: "Sorbonne University",
    location_city: "Paris",
    location_country: "France",
    latitude: 48.8566,
    longitude: 2.3522,
    graduation_year: 2017,
    hl_subjects: ["Film", "English Literature", "French A"],
    hl_teachers: ["Ms. Laurent", "Mr. Dubois"],
    current_profession: "Documentary Filmmaker",
    advice_to_students:
      "The IB's emphasis on different perspectives is exactly what makes great storytelling. Embrace the breadth of subjects.",
    favourite_memory:
      "Screening our Film HL short in the school theatre and getting a standing ovation from Year 7s.",
    took_gap_year: true,
    interesting_first_year_class: "French New Wave Cinema",
    linkedin_url: "https://linkedin.com/in/camilledubois",
    open_to_contact: false,
    open_to_mentoring: false,
    consent_given: true,
    status: "approved",
    created_at: "2024-04-12T15:45:00Z",
  },
  {
    id: "10",
    full_name: "Lucas Silva",
    undergraduate_degree: "MD Medicine",
    university: "University of Sao Paulo",
    location_city: "Sao Paulo",
    location_country: "Brazil",
    latitude: -23.5505,
    longitude: -46.6333,
    graduation_year: 2014,
    hl_subjects: ["Biology", "Chemistry", "Spanish B"],
    hl_teachers: ["Dr. Patel", "Ms. Garcia"],
    current_profession: "Emergency Medicine Physician",
    advice_to_students:
      "If you want to do medicine, the IB is the best preparation. The workload trains you for the intensity of medical school.",
    favourite_memory:
      "The CAS trip to a rural clinic in Ecuador where I first knew I wanted to be a doctor.",
    took_gap_year: false,
    interesting_first_year_class: "Human Anatomy",
    linkedin_url: "https://linkedin.com/in/lucassilva",
    open_to_contact: true,
    open_to_mentoring: true,
    consent_given: true,
    status: "approved",
    created_at: "2024-02-18T12:00:00Z",
  },
  {
    id: "11",
    full_name: "Naledi Mbeki",
    undergraduate_degree: "BA Law (LLB)",
    university: "University of Cape Town",
    location_city: "Cape Town",
    location_country: "South Africa",
    latitude: -33.9249,
    longitude: 18.4241,
    graduation_year: 2016,
    hl_subjects: ["History", "English Literature", "Economics"],
    hl_teachers: ["Ms. Williams", "Mr. Garcia"],
    current_profession: "Human Rights Lawyer at Legal Resources Centre",
    advice_to_students:
      "Write your Extended Essay on something you're passionate about, not what you think looks impressive. Authenticity matters.",
    favourite_memory:
      "The whole-school debate on climate justice that our TOK teacher organised. It felt like we were actually changing minds.",
    took_gap_year: true,
    interesting_first_year_class: "Constitutional Law and Human Rights",
    linkedin_url: "https://linkedin.com/in/naledimbeki",
    open_to_contact: true,
    open_to_mentoring: true,
    consent_given: true,
    status: "approved",
    created_at: "2024-03-22T09:30:00Z",
  },
  {
    id: "12",
    full_name: "Erik Lindqvist",
    undergraduate_degree: "MSc Environmental Science",
    university: "KTH Royal Institute of Technology",
    location_city: "Stockholm",
    location_country: "Sweden",
    latitude: 59.3293,
    longitude: 18.0686,
    graduation_year: 2018,
    hl_subjects: ["Biology", "Geography", "Mathematics"],
    hl_teachers: ["Dr. Svensson", "Mr. Thompson"],
    current_profession: "Sustainability Consultant at McKinsey",
    advice_to_students:
      "HL Geography is underrated. It gave me systems thinking skills that are incredibly valuable in the sustainability space.",
    favourite_memory:
      "The geography field trip to Iceland where we stood on the Mid-Atlantic Ridge and could literally see two tectonic plates.",
    took_gap_year: false,
    interesting_first_year_class: "Climate Systems and Global Change",
    linkedin_url: "https://linkedin.com/in/eriklindqvist",
    open_to_contact: true,
    open_to_mentoring: false,
    consent_given: true,
    status: "approved",
    created_at: "2024-01-30T14:15:00Z",
  },
  {
    id: "13",
    full_name: "Priya Sharma",
    undergraduate_degree: "BA Psychology",
    university: "University of Mumbai",
    location_city: "Mumbai",
    location_country: "India",
    latitude: 19.076,
    longitude: 72.8777,
    graduation_year: 2020,
    hl_subjects: ["Psychology", "Biology", "English Literature"],
    hl_teachers: ["Dr. Gupta", "Ms. Williams"],
    current_profession: "Clinical Psychologist at Tata Memorial Hospital",
    advice_to_students:
      "HL Psychology changed how I see the world. If you're interested in people, take it -- the IA research skills are directly applicable to university.",
    favourite_memory:
      "Running the school's peer support programme as part of CAS and seeing it actually help students during exam season.",
    took_gap_year: false,
    interesting_first_year_class: "Cognitive Neuroscience",
    linkedin_url: "https://linkedin.com/in/priyasharma",
    open_to_contact: true,
    open_to_mentoring: true,
    consent_given: true,
    status: "approved",
    created_at: "2024-04-05T11:00:00Z",
  },
  {
    id: "14",
    full_name: "Daniel Park",
    undergraduate_degree: "BEng Electrical Engineering",
    university: "University of Toronto",
    location_city: "Toronto",
    location_country: "Canada",
    latitude: 43.6532,
    longitude: -79.3832,
    graduation_year: 2017,
    hl_subjects: ["Physics", "Mathematics", "Computer Science"],
    hl_teachers: ["Mr. Thompson", "Dr. Kim"],
    current_profession: "Robotics Engineer at Clearpath Robotics",
    advice_to_students:
      "The IA in Physics taught me how to design experiments properly. That skill is priceless in engineering.",
    favourite_memory:
      "The physics teacher dropping a watermelon from the roof to demonstrate terminal velocity. It was meant to be educational but it was pure chaos.",
    took_gap_year: false,
    interesting_first_year_class: "Signals and Systems",
    linkedin_url: "https://linkedin.com/in/danielpark",
    open_to_contact: true,
    open_to_mentoring: true,
    consent_given: true,
    status: "approved",
    created_at: "2024-02-05T08:45:00Z",
  },
  {
    id: "15",
    full_name: "Isabella Cheung",
    undergraduate_degree: "BA Fine Arts",
    university: "Hong Kong University",
    location_city: "Hong Kong",
    location_country: "China",
    latitude: 22.3193,
    longitude: 114.1694,
    graduation_year: 2021,
    hl_subjects: ["Visual Arts", "English Literature", "History"],
    hl_teachers: ["Ms. O'Brien", "Mr. Dubois"],
    current_profession: "Gallery Curator at White Cube Hong Kong",
    advice_to_students:
      "Don't let anyone tell you the arts aren't 'serious' IB subjects. My HL Visual Arts portfolio got me into every university I applied to.",
    favourite_memory:
      "The collaborative mural project where every Year 13 student contributed a panel. It's still hanging in the school corridor.",
    took_gap_year: true,
    interesting_first_year_class: "Contemporary Asian Art History",
    linkedin_url: "https://linkedin.com/in/isabellacheung",
    open_to_contact: true,
    open_to_mentoring: false,
    consent_given: true,
    status: "approved",
    created_at: "2024-03-10T16:30:00Z",
  },
];

export const allHLSubjects = [
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "Computer Science",
  "Economics",
  "Business Management",
  "History",
  "Geography",
  "Psychology",
  "English Literature",
  "Visual Arts",
  "Film",
  "Design Technology",
  "French A",
  "French B",
  "Spanish B",
  "Chinese B",
];

export const allCareerFields = [
  ...new Set(sampleAlumni.map((a) => a.current_profession.split(" at ")[0])),
];
